### ISSUE TITLE
PM_CATWISE overlay also enables CATWISE overlay

### ISSUE THREAD

**Issue by MrtnKk** [fkiwy/AstroToolBox#28]
### Describe the bug:
When I enable the PM_CATWISE overlay, 'Save selected overlays' and restart ATB then the other CATWISE overlay gets enabled as well after restart.

### Steps to reproduce the problem:
1. Open `AstroToolBox.properties` and remove everything behind `overlays=`
2. Save the file and then start ATB
3. Enable the PM_CatWISE overlay and '**Save selected overlays**'
4. Quit and Restart ATB - now both CatWISE overlays are enabled

### Expected behavior:
Only the PM_CATWISE overlay should be enabled.

**Desktop:**
 - OS: Ubuntu 18.04.06 LTS

**Comment by fkiwy** [comment]
There's a new ATB version available [here](https://fkiwy.github.io/AstroToolBox/releases/executables/AstroToolBox-2.5.1.jar), which should fix the bug described above.
@MrtnKk Can you confirm that this bug has been fixed with version 2.5.1 ?

**Comment by MrtnKk** [comment]
Yep, the bug seems fixed. :+1:  

Had to resave the selected overlays once again though because the `overlays` variable in the properties file still listed the old values. So when I first opened version 2.5.1, the regular CatWISE overlay was enabled instead of the PM_CATWISE one.
